#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt AUTO_NAME_DIRS
setopt interactivecomments
bindkey -e

function vimeo-ref-dl() {
   local URL=$(osascript -e "tell application \"Safari\" to return URL of front document")
   youtube-dl -f "bestvideo+bestaudio/best" --merge-output-format mkv             \
                                            --output "%(title)s.%(ext)s"          \
                                            --referer "$URL"                      \
                                            "https://player.vimeo.com/video/$1"
 }