#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt AUTO_NAME_DIRS
setopt interactivecomments
bindkey -e

function vimeo-ref-dl() {
   local URL=$(osascript -e "tell application \"Safari\" to return URL of front document")
   youtube-dl -f "bestvideo+bestaudio/best" --merge-output-format mkv             \
                                            --output "%(title)s.%(ext)s"          \
                                            --referer "$URL"                      \
                                            "https://player.vimeo.com/video/$1"
 }
# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

# Secretive
export SSH_AUTH_SOCK=/Users/matteo/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

cat ~/.cache/wal/sequences

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

alias l="exa -lh"
alias ll="exa -lhF"
alias la="exa -lahF"
